module.exports = {
    COMMUNITY_CHAT: "COMMUNITY_CHAT",
    USER_RECONNECTED: "USER_RECONNECTED",
    MESSAGE_RECEIVED: "MESSAGE_RECEIVED",
    MESSAGE_SENT: "MESSAGE_SENT",
    USER_DISCONNECTED: "USER_DISCONNECTED",
    TYPING: "TYPING",
    VERIFY_USER: "VERIFY_USER",
    LOGOUT: "LOGOUT",
    LOGIN: "LOGIN",
    SEND_PRIVATE_MESSAGE: "SEND_PRIVATE_MESSAGE",
    RECEIVE_PRIVATE_MESSAGE: "RECEIVE_PRIVATE_MESSAGE",
    CREATE_NEW_CHAT: "CREATE_NEW_CHAT",
    RECEIVE_NEW_CHAT: "RECEIVE_NEW_CHAT",
    RECEIVE_ALL_CHATS: "RECEIVE_ALL_CHATS"
}